title: Moumita Basu
logo: /assets/headshot_2.jpg
description: ğŸš€ Writing code, optimizing workflows, and solving business problems with Python, AI, and a little bit of magic! ğŸ
#show_downloads: false
theme: jekyll-theme-minimal
